#pragma once
#include "FST.h"
#define N_GRAPHS 25

#define GRAPH_SEPARATORS 2,\
	FST::NODE(19,\
			FST::RELATION(';',1), FST::RELATION('=',1),\
			FST::RELATION(',',1), FST::RELATION('{',1),\
			FST::RELATION('}',1), FST::RELATION('(',1),\
			FST::RELATION(')',1), FST::RELATION('^',1),\
			FST::RELATION(':',1), FST::RELATION('<',1),\
			FST::RELATION('>',1), FST::RELATION('&',1),\
			FST::RELATION('|',1), FST::RELATION('!',1),\
			FST::RELATION('+',1), FST::RELATION('-',1),\
			FST::RELATION('*',1), FST::RELATION('/',1),\
			FST::RELATION('%',1)),\
	FST::NODE()

#define GRAPH_ID 2, \
	FST::NODE(52, \
        FST::RELATION('a', 1), FST::RELATION('b', 1), FST::RELATION('c', 1), FST::RELATION('d', 1), \
        FST::RELATION('e', 1), FST::RELATION('f', 1), FST::RELATION('g', 1), FST::RELATION('h', 1), \
        FST::RELATION('i', 1), FST::RELATION('j', 1), FST::RELATION('k', 1), FST::RELATION('l', 1), \
        FST::RELATION('m', 1), FST::RELATION('n', 1), FST::RELATION('o', 1), FST::RELATION('p', 1), \
        FST::RELATION('q', 1), FST::RELATION('r', 1), FST::RELATION('s', 1), FST::RELATION('t', 1), \
        FST::RELATION('u', 1), FST::RELATION('v', 1), FST::RELATION('w', 1), FST::RELATION('x', 1), \
        FST::RELATION('y', 1), FST::RELATION('z', 1), \
        FST::RELATION('A', 1), FST::RELATION('B', 1), FST::RELATION('C', 1), FST::RELATION('D', 1), \
        FST::RELATION('E', 1), FST::RELATION('F', 1), FST::RELATION('G', 1), FST::RELATION('H', 1), \
        FST::RELATION('I', 1), FST::RELATION('J', 1), FST::RELATION('K', 1), FST::RELATION('L', 1), \
        FST::RELATION('M', 1), FST::RELATION('N', 1), FST::RELATION('O', 1), FST::RELATION('P', 1), \
        FST::RELATION('Q', 1), FST::RELATION('R', 1), FST::RELATION('S', 1), FST::RELATION('T', 1), \
        FST::RELATION('U', 1), FST::RELATION('V', 1), FST::RELATION('W', 1), FST::RELATION('X', 1), \
        FST::RELATION('Y', 1), FST::RELATION('Z', 1)), \
	FST::NODE(62, \
        FST::RELATION('a', 1), FST::RELATION('b', 1), FST::RELATION('c', 1), FST::RELATION('d', 1), \
        FST::RELATION('e', 1), FST::RELATION('f', 1), FST::RELATION('g', 1), FST::RELATION('h', 1), \
        FST::RELATION('i', 1), FST::RELATION('j', 1), FST::RELATION('k', 1), FST::RELATION('l', 1), \
        FST::RELATION('m', 1), FST::RELATION('n', 1), FST::RELATION('o', 1), FST::RELATION('p', 1), \
        FST::RELATION('q', 1), FST::RELATION('r', 1), FST::RELATION('s', 1), FST::RELATION('t', 1), \
        FST::RELATION('u', 1), FST::RELATION('v', 1), FST::RELATION('w', 1), FST::RELATION('x', 1), \
        FST::RELATION('y', 1), FST::RELATION('z', 1), \
        FST::RELATION('A', 1), FST::RELATION('B', 1), FST::RELATION('C', 1), FST::RELATION('D', 1), \
        FST::RELATION('E', 1), FST::RELATION('F', 1), FST::RELATION('G', 1), FST::RELATION('H', 1), \
        FST::RELATION('I', 1), FST::RELATION('J', 1), FST::RELATION('K', 1), FST::RELATION('L', 1), \
        FST::RELATION('M', 1), FST::RELATION('N', 1), FST::RELATION('O', 1), FST::RELATION('P', 1), \
        FST::RELATION('Q', 1), FST::RELATION('R', 1), FST::RELATION('S', 1), FST::RELATION('T', 1), \
        FST::RELATION('U', 1), FST::RELATION('V', 1), FST::RELATION('W', 1), FST::RELATION('X', 1), \
        FST::RELATION('Y', 1), FST::RELATION('Z', 1), \
        FST::RELATION('0', 1), FST::RELATION('1', 1), FST::RELATION('2', 1), FST::RELATION('3', 1), \
        FST::RELATION('4', 1), FST::RELATION('5', 1), FST::RELATION('6', 1), FST::RELATION('7', 1), \
        FST::RELATION('8', 1), FST::RELATION('9', 1))

#define GRAPH_STRING_LITERAL 3,\
	FST::NODE(1, FST::RELATION('\"', 1)),\
	FST::NODE(87, \
			FST::RELATION(' ', 1), FST::RELATION(':', 1), FST::RELATION('=', 1), FST::RELATION('*', 1), \
            FST::RELATION('!', 1), FST::RELATION('?', 1), FST::RELATION(',', 1), FST::RELATION('.', 1), \
            FST::RELATION(';', 1), FST::RELATION('-', 1), FST::RELATION('+', 1), FST::RELATION('/', 1), \
            FST::RELATION('(', 1), FST::RELATION(')', 1), FST::RELATION('{', 1), FST::RELATION('}', 1), \
            FST::RELATION('[', 1), FST::RELATION(']', 1), FST::RELATION('%', 1), FST::RELATION('_', 1), \
            FST::RELATION('&', 1), FST::RELATION('>', 1), FST::RELATION('<', 1), FST::RELATION('^', 1), \
            FST::RELATION('a', 1), FST::RELATION('b', 1), FST::RELATION('c', 1), FST::RELATION('d', 1),\
            FST::RELATION('e', 1), FST::RELATION('f', 1), FST::RELATION('g', 1), FST::RELATION('h', 1),\
            FST::RELATION('i', 1), FST::RELATION('j', 1), FST::RELATION('k', 1), FST::RELATION('l', 1),\
            FST::RELATION('m', 1), FST::RELATION('n', 1), FST::RELATION('o', 1), FST::RELATION('p', 1),\
            FST::RELATION('q', 1), FST::RELATION('r', 1), FST::RELATION('s', 1), FST::RELATION('t', 1),\
            FST::RELATION('u', 1), FST::RELATION('v', 1), FST::RELATION('w', 1), FST::RELATION('x', 1),\
            FST::RELATION('y', 1), FST::RELATION('z', 1),\
            FST::RELATION('A', 1), FST::RELATION('B', 1), FST::RELATION('C', 1), FST::RELATION('D', 1),\
            FST::RELATION('E', 1), FST::RELATION('F', 1), FST::RELATION('G', 1), FST::RELATION('H', 1),\
            FST::RELATION('I', 1), FST::RELATION('J', 1), FST::RELATION('K', 1), FST::RELATION('L', 1),\
            FST::RELATION('M', 1), FST::RELATION('N', 1), FST::RELATION('O', 1), FST::RELATION('P', 1),\
            FST::RELATION('Q', 1), FST::RELATION('R', 1), FST::RELATION('S', 1), FST::RELATION('T', 1),\
            FST::RELATION('U', 1), FST::RELATION('V', 1), FST::RELATION('W', 1), FST::RELATION('X', 1),\
            FST::RELATION('Y', 1), FST::RELATION('Z', 1),\
            FST::RELATION('0', 1), FST::RELATION('1', 1), FST::RELATION('2', 1), FST::RELATION('3', 1),\
            FST::RELATION('4', 1), FST::RELATION('5', 1), FST::RELATION('6', 1), FST::RELATION('7', 1),\
            FST::RELATION('8', 1), FST::RELATION('9', 1),\
			FST::RELATION('\"', 2)), \
	FST::NODE()

#define GRAPH_EQUAL 3,\
	FST::NODE(1, FST::RELATION('=',1)),\
	FST::NODE(1, FST::RELATION('=',2)),\
	FST::NODE()

#define GRAPH_NOTEQUAL 3,\
	FST::NODE(1, FST::RELATION('!',1)),\
	FST::NODE(1, FST::RELATION('=',2)),\
	FST::NODE()

#define GRAPH_GREATEREQ 3,\
	FST::NODE(1, FST::RELATION('>',1)),\
	FST::NODE(1, FST::RELATION('=',2)),\
	FST::NODE()

#define GRAPH_LESSEQ 3,\
	FST::NODE(1, FST::RELATION('<',1)),\
	FST::NODE(1, FST::RELATION('=',2)),\
	FST::NODE()

#define GRAPH_INT_LITERAL 2, \
	FST::NODE(10, \
			FST::RELATION('0',1),FST::RELATION('1',1),FST::RELATION('2',1),FST::RELATION('3',1),\
			FST::RELATION('4',1),FST::RELATION('5',1),FST::RELATION('6',1),FST::RELATION('7',1),\
			FST::RELATION('8',1),FST::RELATION('9',1)),\
	FST::NODE(10,\
			FST::RELATION('0',1),FST::RELATION('1',1),FST::RELATION('2',1),FST::RELATION('3',1),\
			FST::RELATION('4',1),FST::RELATION('5',1),FST::RELATION('6',1),FST::RELATION('7',1),\
			FST::RELATION('8',1),FST::RELATION('9',1))

#define GRAPH_VAR 4, \
	FST::NODE(1,FST::RELATION('a',1)),\
	FST::NODE(1,FST::RELATION('d',2)),\
	FST::NODE(1,FST::RELATION('v',3)),\
	FST::NODE()

#define GRAPH_MAIN 5, \
	FST::NODE(1,FST::RELATION('m',1)),\
	FST::NODE(1,FST::RELATION('a',2)),\
	FST::NODE(1,FST::RELATION('i',3)),\
	FST::NODE(1,FST::RELATION('n',4)),\
	FST::NODE()

#define GRAPH_UINT 5,\
	FST::NODE(1, FST::RELATION('u',1)),\
	FST::NODE(1, FST::RELATION('i',2)),\
	FST::NODE(1, FST::RELATION('n',3)),\
	FST::NODE(1, FST::RELATION('t',4)),\
	FST::NODE()

#define GRAPH_STRING 7, \
	FST::NODE(1, FST::RELATION('s',1)),\
	FST::NODE(1, FST::RELATION('t',2)),\
	FST::NODE(1, FST::RELATION('r',3)),\
	FST::NODE(1, FST::RELATION('i',4)),\
	FST::NODE(1, FST::RELATION('n',5)),\
	FST::NODE(1, FST::RELATION('g',6)),\
	FST::NODE()

#define GRAPH_FUNCTION 9, \
	FST::NODE(1, FST::RELATION('f', 1)),\
    FST::NODE(1, FST::RELATION('u', 2)),\
    FST::NODE(1, FST::RELATION('n', 3)),\
    FST::NODE(1, FST::RELATION('c', 4)),\
    FST::NODE(1, FST::RELATION('t', 5)),\
    FST::NODE(1, FST::RELATION('i', 6)),\
    FST::NODE(1, FST::RELATION('o', 7)),\
    FST::NODE(1, FST::RELATION('n', 8)),\
    FST::NODE()

#define GRAPH_RETURN 7, \
	FST::NODE(1, FST::RELATION('r',1)),\
	FST::NODE(1, FST::RELATION('e',2)),\
	FST::NODE(1, FST::RELATION('t',3)),\
	FST::NODE(1, FST::RELATION('u',4)),\
	FST::NODE(1, FST::RELATION('r',5)),\
	FST::NODE(1, FST::RELATION('n',6)),\
	FST::NODE()

#define GRAPH_WRITE 5, \
	FST::NODE(1, FST::RELATION('c',1)),\
	FST::NODE(1, FST::RELATION('o',2)),\
	FST::NODE(1, FST::RELATION('u',3)),\
	FST::NODE(1, FST::RELATION('t',4)),\
	FST::NODE()

#define GRAPH_SWITCH 7, \
	FST::NODE(1, FST::RELATION('s',1)),\
	FST::NODE(1, FST::RELATION('w',2)),\
	FST::NODE(1, FST::RELATION('i',3)),\
	FST::NODE(1, FST::RELATION('t',4)),\
	FST::NODE(1, FST::RELATION('c',5)),\
	FST::NODE(1, FST::RELATION('h',6)),\
	FST::NODE()

#define GRAPH_CASE 5, \
	FST::NODE(1, FST::RELATION('c',1)),\
	FST::NODE(1, FST::RELATION('a',2)),\
	FST::NODE(1, FST::RELATION('s',3)),\
	FST::NODE(1, FST::RELATION('e',4)),\
	FST::NODE()

#define GRAPH_DEFAULT 8, \
	FST::NODE(1, FST::RELATION('d',1)),\
	FST::NODE(1, FST::RELATION('e',2)),\
	FST::NODE(1, FST::RELATION('f',3)),\
	FST::NODE(1, FST::RELATION('a',4)),\
	FST::NODE(1, FST::RELATION('u',5)),\
	FST::NODE(1, FST::RELATION('l',6)),\
	FST::NODE(1, FST::RELATION('t',7)),\
	FST::NODE()

#define GRAPH_HEX_LITERAL 4, \
    FST::NODE(2, FST::RELATION('-', 0), FST::RELATION('0', 1)), \
    FST::NODE(2, FST::RELATION('x', 2), FST::RELATION('X', 2)), \
    FST::NODE(44, \
		FST::RELATION('0', 2), FST::RELATION('1', 2), FST::RELATION('2', 2), FST::RELATION('3', 2), \
        FST::RELATION('4', 2), FST::RELATION('5', 2), FST::RELATION('6', 2), FST::RELATION('7', 2), \
        FST::RELATION('8', 2), FST::RELATION('9', 2), FST::RELATION('A', 2), FST::RELATION('B', 2), \
        FST::RELATION('C', 2), FST::RELATION('D', 2), FST::RELATION('E', 2), FST::RELATION('F', 2), \
        FST::RELATION('a', 2), FST::RELATION('b', 2), FST::RELATION('c', 2), FST::RELATION('d', 2), \
        FST::RELATION('e', 2), FST::RELATION('f', 2) ,\
        FST::RELATION('0', 3), FST::RELATION('1', 3), FST::RELATION('2', 3), FST::RELATION('3', 3), \
        FST::RELATION('4', 3), FST::RELATION('5', 3), FST::RELATION('6', 3), FST::RELATION('7', 3), \
        FST::RELATION('8', 3), FST::RELATION('9', 3), FST::RELATION('A', 3), FST::RELATION('B', 3), \
        FST::RELATION('C', 3), FST::RELATION('D', 3), FST::RELATION('E', 3), FST::RELATION('F', 3), \
        FST::RELATION('a', 3), FST::RELATION('b', 3), FST::RELATION('c', 3), FST::RELATION('d', 3), \
        FST::RELATION('e', 3), FST::RELATION('f', 3) \
    ), \
    FST::NODE()

#define GRAPH_WHILE 6, \
	FST::NODE(1, FST::RELATION('w',1)),\
	FST::NODE(1, FST::RELATION('h',2)),\
	FST::NODE(1, FST::RELATION('i',3)),\
	FST::NODE(1, FST::RELATION('l',4)),\
	FST::NODE(1, FST::RELATION('e',5)),\
	FST::NODE()

#define GRAPH_STRTOUINT 16, \
	FST::NODE(1, FST::RELATION('s',1)),\
	FST::NODE(1, FST::RELATION('t',2)),\
	FST::NODE(1, FST::RELATION('r',3)),\
	FST::NODE(1, FST::RELATION('i',4)),\
	FST::NODE(1, FST::RELATION('n',5)),\
	FST::NODE(1, FST::RELATION('g',6)),\
	FST::NODE(1, FST::RELATION('T',7)),\
	FST::NODE(1, FST::RELATION('o',8)),\
	FST::NODE(1, FST::RELATION('U',9)),\
	FST::NODE(1, FST::RELATION('n',10)),\
	FST::NODE(1, FST::RELATION('s',11)),\
	FST::NODE(1, FST::RELATION('i',12)),\
	FST::NODE(1, FST::RELATION('g',13)),\
	FST::NODE(1, FST::RELATION('n',14)),\
	FST::NODE(1, FST::RELATION('e',15)),\
	FST::NODE(1, FST::RELATION('d',16)),\
	FST::NODE()

#define GRAPH_UINTTOSTR 16, \
	FST::NODE(1, FST::RELATION('u',1)),\
	FST::NODE(1, FST::RELATION('n',2)),\
	FST::NODE(1, FST::RELATION('s',3)),\
	FST::NODE(1, FST::RELATION('i',4)),\
	FST::NODE(1, FST::RELATION('g',5)),\
	FST::NODE(1, FST::RELATION('n',6)),\
	FST::NODE(1, FST::RELATION('e',7)),\
	FST::NODE(1, FST::RELATION('d',8)),\
	FST::NODE(1, FST::RELATION('T',9)),\
	FST::NODE(1, FST::RELATION('o',10)),\
	FST::NODE(1, FST::RELATION('S',11)),\
	FST::NODE(1, FST::RELATION('t',12)),\
	FST::NODE(1, FST::RELATION('r',13)),\
	FST::NODE(1, FST::RELATION('i',14)),\
	FST::NODE(1, FST::RELATION('n',15)),\
	FST::NODE(1, FST::RELATION('g',16)),\
	FST::NODE()

#define GRAPH_STRLEN 13, \
	FST::NODE(1, FST::RELATION('s',1)),\
	FST::NODE(1, FST::RELATION('t',2)),\
	FST::NODE(1, FST::RELATION('r',3)),\
	FST::NODE(1, FST::RELATION('i',4)),\
	FST::NODE(1, FST::RELATION('n',5)),\
	FST::NODE(1, FST::RELATION('g',6)),\
	FST::NODE(1, FST::RELATION('L',7)),\
	FST::NODE(1, FST::RELATION('e',8)),\
	FST::NODE(1, FST::RELATION('n',9)),\
	FST::NODE(1, FST::RELATION('g',10)),\
	FST::NODE(1, FST::RELATION('t',11)),\
	FST::NODE(1, FST::RELATION('h',12)),\
	FST::NODE()

#define GRAPH_STRCAT 13, \
	FST::NODE(1, FST::RELATION('s',1)),\
	FST::NODE(1, FST::RELATION('t',2)),\
	FST::NODE(1, FST::RELATION('r',3)),\
	FST::NODE(1, FST::RELATION('i',4)),\
	FST::NODE(1, FST::RELATION('n',5)),\
	FST::NODE(1, FST::RELATION('g',6)),\
	FST::NODE(1, FST::RELATION('C',7)),\
	FST::NODE(1, FST::RELATION('o',8)),\
	FST::NODE(1, FST::RELATION('n',9)),\
	FST::NODE(1, FST::RELATION('c',10)),\
	FST::NODE(1, FST::RELATION('a',11)),\
	FST::NODE(1, FST::RELATION('t',12)),\
	FST::NODE()